name: simco Project Publish to cPanel

on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action codes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: "ftp.chapelsage.space"
          ftp-username: "ftp_simco@simcoenterprise.com"
          ftp-password: "[6KT#uEElt$m"
          server-dir: "/home/chapmpug/simcoenterprise.com/"
